"""add_progress_pct_to_reviews

Revision ID: 9698a0479c6a
Revises: 002
Create Date: 2026-08-16 22:37:46.068918

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "9698a0479c6a"
down_revision: str | Sequence[str] | None = "002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reviews", sa.Column("progress_pct", sa.Integer(), server_default="0", nullable=False)
    )
    op.execute("UPDATE reviews SET progress_pct = 100 WHERE status = 'complete'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "progress_pct")
    # ### end Alembic commands ###
